# Generated by Django 4.0.6 on 2022-09-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('tipocategoria', models.CharField(blank=True, db_column='tipoCategoria', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Categorias',
                'managed': False,
            },
        ),
    ]
