# Generated by Django 4.0.6 on 2022-09-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webBukee', '0002_tallas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tallas',
        ),
    ]
