# Generated by Django 4.0.6 on 2022-09-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(db_column='nombreProducto', max_length=50)),
                ('descripcionproducto', models.CharField(db_column='descripcionProducto', max_length=50)),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('talla', models.AutoField(db_column='Talla', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tallas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
