# Generated by Django 4.0.6 on 2022-09-09 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_tallas_delete_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Productos'},
        ),
    ]
