# Generated by Django 4.0.6 on 2022-09-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_tallas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tallas',
        ),
    ]
